# render.yaml
services:
  - type: web
    name: pesapal-rdbms
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pesapal-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
    healthCheckPath: /admin/
    autoDeploy: true

databases:
  - name: pesapal-db
    databaseName: pesapal
    user: pesapal_user
    plan: free