services:
  - type: web
    name: pesapal-rdbms
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn web.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: pesapal-db
          property: connectionString
    healthCheckPath: /admin/

databases:
  - name: pesapal-db
    databaseName: pesapal
    user: pesapal_user
    plan: free